MPESA_CONSUMER_KEY: '3frEilhnCma2pvwXZ2u1kP8ko7GexvSW'
MPESA_CONSUMER_SECRET: 'IKhXG8wTtKFMCJD7'
MPESA_SHORTCODE: '174379'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_SECURITY_CREDENTIAL: 'safaricom984!'
MPESA_CALLBACK_URL: 'https://3f3b-105-160-88-245.ngrok-free.app'
REGISTER_API_URL: 'https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl'
MPESA_QUERY_URL: 'https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query'
